# Generated by Django 4.2.11 on 2024-05-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_product_catalog_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=100)),
                ('reseller_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Warehose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('product_class', models.CharField(choices=[('own', 'Propio'), ('external', 'Externo')], default='external', max_length=50)),
                ('warehouse_location', models.CharField(max_length=200)),
                ('warehouse_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product_brand',
            name='brand_state',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_inventory',
            name='store',
            field=models.CharField(choices=[('main', 'Bodega Principal'), ('digicorp', 'Digicorp')], default='main', max_length=50),
        ),
    ]
