# Generated by Django 4.2.11 on 2024-05-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_rename_warehose_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_catalog',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product_inventory',
            name='sku',
        ),
        migrations.DeleteModel(
            name='Product_reseller',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='Product_brand',
        ),
        migrations.DeleteModel(
            name='Product_catalog',
        ),
        migrations.DeleteModel(
            name='Product_inventory',
        ),
    ]
