# Generated by Django 4.2.11 on 2024-05-07 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0005_remove_product_catalog_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('information', models.TextField(max_length=500)),
                ('warranty_days', models.IntegerField()),
                ('product_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product_brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product_reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=100)),
                ('reseller_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_logs', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100, unique=True)),
                ('warehouse_class', models.CharField(choices=[('own', 'Propio'), ('external', 'Externo')], default='external', max_length=50)),
                ('warehouse_location', models.CharField(max_length=200)),
                ('warehouse_state', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('canceled', 'Cancelado')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.IntegerField()),
                ('reserved', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product_catalog')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.warehouse')),
            ],
        ),
    ]
