# Generated by Django 4.2.11 on 2024-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_catalog',
            name='warranty_days',
            field=models.IntegerField(default=0),
        ),
    ]
